global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

remote_write:
  - url: "**<Remote Write Endpoint>**"
    basic_auth:
      username: "**<Username / Instance ID>**"
      password: "**<Password / API Key>**"
